# -*- coding: utf-8 -*-
"""etl_corredores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpIq5S5qUedWLIbaGZ3VePDwI0HNl-l7
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

corredores = pd.read_csv(url)
corredores.head()

#EXPLORACION DE DATOS

#corredores.shape #filas, columnas
#corredores.columns
#corredores.info()
#corredores.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(corredores):
    corredores.columns = (
        corredores.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return corredores

# Limpia solamente textos
def limpiar_texto(corredores):
    for col in corredores.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        corredores[col] = corredores[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        corredores[col] = corredores[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return corredores

#APLICA LIMPIEZA GENERAL
corredores = normalizar_columnas(corredores)
corredores = limpiar_texto(corredores)
corredores = corredores.drop_duplicates() #Elimina duplicados

#LIMPIEZA DE DATOS ESPECIFICOS

#nombre
import unicodedata

corredores["nombre"] = (
    corredores["nombre"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)

#zona
corredores["zona"] = (
    corredores ["zona"].astype(str).str.strip().str.lower().map({
        "occidente":"Occidental",
        "paracentral":"Paracentral",
        "costa":"Costa",
        "centro":"Central",
        "oriente":"Oriental"
    })
)

corredores["zona"] = corredores["zona"].fillna("No Especificado")

#nivel
corredores["nivel"] = (
    corredores ["nivel"].astype(str).str.strip().str.lower().map({
        "junior":"Junior",
        "mid":"Mid",
        "senior":"Senior"
    })
)

corredores["nivel"] = corredores["nivel"].fillna("No Especificado")

#anios_experiencia
corredores["anios_experiencia"] = pd.to_numeric(corredores["anios_experiencia"], errors="coerce")
corredores["anios_experiencia"] = corredores["anios_experiencia"].fillna("No Especificado")

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

condicion = ["No Especificado"]

corredores_validos = corredores[
    ~corredores[['id_corredor','nombre','zona','nivel','anios_experiencia']]
    .isin(condicion)
    .any(axis=1)
].copy()

corredores_rechazados = corredores[
    corredores[['id_corredor','nombre','zona','nivel','anios_experiencia']]
    .isin(condicion)
    .any(axis=1)
].copy()

# MOTIVO DE RECHAZO

def motivo(row):
    motivos = []

    if row['id_corredor'] == "No Especificado":
        motivos.append("idCorredor_noEspecificado")

    if row['nombre'] == "No Especificado":
        motivos.append("nombre_noEspecificado")

    if row['zona'] == "No Especificado":
        motivos.append("zona_noEspecificada")

    if row['nivel'] == "No Especificado":
        motivos.append("nivel_noEspecificado")

    if row['anios_experiencia'] == "No Especificado":
        motivos.append("anios_experiencia_noEspecificados")

    return ";".join(motivos)


# aplicar a rechazados
corredores_rechazados["motivo_rechazo"] = corredores_rechazados.apply(motivo, axis=1)

#EXPORTAR ARCHIVOS

corredores_validos.to_csv("corredores_curated.csv", index=False)

corredores_rechazados.to_csv("corredores_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

if corredores_validos.empty:
    print("⚠ No hay datos válidos")

if corredores_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    corredores_validos.to_sql('corredores_curated', engine, if_exists='append', index=False)
    corredores_rechazados.to_sql('corredores_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM corredores_curated LIMIT 10",
    engine
)