# -*- coding: utf-8 -*-
"""etl_clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flnANX_NEPtrhzvcHW1wP1voxcWTs3t8
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"

clientes = pd.read_csv(url)
clientes.head()

#EXPLORACION DE DATOS

#clientes.shape #filas, columnas
#clientes.columns
#clientes.info()
#clientes.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(clientes):
    clientes.columns = (
        clientes.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return clientes

# Limpia solamente textos
def limpiar_texto(clientes):
    for col in clientes.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        clientes[col] = clientes[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        clientes[col] = clientes[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return clientes

#APLICA LIMPIEZA GENERAL
clientes = normalizar_columnas(clientes)
clientes = limpiar_texto(clientes)
clientes=clientes.drop_duplicates() #Elimina duplicados

from pandas.core.tools.datetimes import to_datetime
#LIMPIEZA DE DATOS ESPECIFICOS

#Nombre
import unicodedata

clientes["nombre"] = (
    clientes["nombre"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)

#Email
clientes["email"] = clientes["email"].astype(str).str.lower().str.strip()

#Genero
clientes["genero"] = (
    clientes ["genero"].astype(str).str.strip().str.lower().map({
        "hombre":"Masculino",
        "masculino":"Masculino",
        "m":"Masculino",
        "mujer":"Femenino",
        "femenino":"Femenino",
        "f":"Femenino",
        "fem":"Femenino",
        "female":"Femenino"
    })
)

#Ciudad
clientes["ciudad"] = (
    clientes["ciudad"].astype(str).str.strip().str.lower().replace({
        "sanmiguel":"san miguel",
        "s. miguel":"san miguel",
        "sta. ana":"santa ana",
        "staana":"santa ana",
        "santaana":"santa ana",
        "ss":"san salvador",
        "sansalvador": "san salvador",
        "lalibertad":"la libertad",
        "l. libertad":"la libertad",
        "sonso":"sonsonate"
        }).str.title()
)


#Fecha de nacimiento
clientes["fecha_nacimiento"] = pd.to_datetime(clientes["fecha_nacimiento"],errors="coerce",dayfirst=False)

#Segmento
clientes["segmento"] = clientes["segmento"].fillna("No especificado")

clientes = clientes[["id_cliente","nombre","email","genero","fecha_nacimiento","ciudad","segmento"]].replace(
    ["", " ", "NULL", "null", "None", "nan"],
    pd.NA
)

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

clientes_validos=clientes[
    clientes['id_cliente'].notna()&
    clientes['nombre'].notna()&
    clientes['email'].notna()&
    clientes['genero'].notna()&
    clientes['fecha_nacimiento'].notna()&
    clientes['ciudad'].notna()&
    clientes['segmento'].notna()
].copy()


clientes_rechazados=clientes[
    clientes["id_cliente"].isna() |
    clientes['nombre'].isna() |
    clientes['email'].isna() |
    clientes['genero'].isna() |
    clientes['fecha_nacimiento'].isna() |
    clientes['ciudad'].isna() |
    clientes['segmento'].isna()
].copy()

#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['id_cliente']):
    motivos.append("idCliente_vacio")

  if pd.isna(row['nombre']):
    motivos.append("nombre_vacio")

  if pd.isna(row['email']):
    motivos.append("email_vacio")

  if pd.isna(row['genero']):
    motivos.append("genero_vacio")

  if pd.isna(row['fecha_nacimiento']):
    motivos.append("fechaNacimiento_vacio")

  if pd.isna(row['ciudad']):
    motivos.append("ciudad_vacio")

  if pd.isna(row['segmento']):
    motivos.append("segmento_vacio")

  return ";".join(motivos)

clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo,axis=1)

#VERIFICAR SI HAY DATOS NULOS
print(clientes.isna().sum())

#EXPORTAR ARCHIVOS

clientes_validos.to_csv("clientes_curated.csv", index=False)

clientes_rechazados.to_csv("clientes_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

clientes_validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

clientes_rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM clientes_curated LIMIT 10",
    engine
)