# -*- coding: utf-8 -*-
"""etl_polizas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qXPDHQWNhzroKmNX2ZeO88ZeXZcsmwfa
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

polizas = pd.read_csv(url)
polizas.head(20)

#EXPLORACION DE DATOS

#polizas.shape #filas, columnas
#polizas.columns
#polizas.info()
#polizas.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(polizas):
    polizas.columns = (
        polizas.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return polizas

# Limpia solamente textos
def limpiar_texto(polizas):
    for col in polizas.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        polizas[col] = polizas[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        polizas[col] = polizas[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return polizas

#APLICA LIMPIEZA GENERAL
polizas = normalizar_columnas(polizas)
polizas = limpiar_texto(polizas)
polizas = polizas.drop_duplicates() #Elimina duplicados

#LIMPIEZA DE DATOS ESPECIFICOS

#Fecha de emision
polizas["fecha_emision"] = polizas["fecha_emision"].astype(str).str.strip()
polizas["fecha_emision"] = pd.to_datetime(polizas["fecha_emision"],errors="coerce",dayfirst=True,infer_datetime_format=True)

#Metodo para tipos numericos float:
import numpy as np
def limpiar_monto(x):
    if not isinstance(x, str):
        return x

    # caso: formato europeo (1.234.567,89)
    if "," in x and "." in x:
        if x.rfind(",") > x.rfind("."):
            return x.replace(".", "").replace(",", ".")

    # caso: solo comas → miles (1,000,000)
    if x.count(",") > 1:
        return x.replace(",", "")

    # caso: una coma → decimal
    if "," in x:
        return x.replace(",", ".")

    return x


#Prima
col = polizas["prima"].astype(str).str.strip().str.lower()
# falsos nulos
col = col.replace(r"^\s*-\s*$", np.nan, regex=True)
col = col.replace(["", "none", "nan", "null"], np.nan)
col = col.apply(limpiar_monto)
polizas["prima"] = pd.to_numeric(col, errors="coerce")

#Comision
col = polizas["comision"].astype(str).str.strip().str.lower()
# falsos nulos
col = col.replace(r"^\s*-\s*$", np.nan, regex=True)
col = col.replace(["", "none", "nan", "null"], np.nan)
col = col.apply(limpiar_monto)
polizas["comision"] = pd.to_numeric(col, errors="coerce")

#Monto asegurado
col = polizas["monto_asegurado"].astype(str).str.strip().str.lower()
# falsos nulos
col = col.replace(r"^\s*-\s*$", np.nan, regex=True)
col = col.replace(["", "none", "nan", "null"], np.nan)
col = col.apply(limpiar_monto)
polizas["monto_asegurado"] = pd.to_numeric(col, errors="coerce")

#SEPARAR DATOS INVALIDOS Y RECHAZADOS
polizas_validos=polizas[
    polizas['fecha_emision'].notna()&
    polizas['prima'].notna()&
    polizas['comision'].notna()&
    polizas['monto_asegurado'].notna()
].copy()


polizas_rechazados=polizas[
    polizas["fecha_emision"].isna() |
    polizas['prima'].isna() |
    polizas['comision'].isna() |
    polizas['monto_asegurado'].isna()
].copy()

#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['fecha_emision']):
    motivos.append("fechaEmision_vacia")

  if pd.isna(row['prima']):
    motivos.append("prima_vacia")

  if pd.isna(row['comision']):
    motivos.append("comision_vacia")

  if pd.isna(row['monto_asegurado']):
    motivos.append("montoAsegurado_vacio")

  return ";".join(motivos)

polizas_rechazados["motivo_rechazo"] = polizas_rechazados.apply(motivo,axis=1)

#VERIFICAR SI HAY DATOS NULOS
#print(polizas.isna().sum())
#polizas
#polizas_rechazados["motivo_rechazo"].value_counts()

#EXPORTAR ARCHIVOS

polizas_validos.to_csv("polizas_curated.csv", index=False)

polizas_rechazados.to_csv("polizas_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

if polizas_validos.empty:
    print("⚠ No hay datos válidos")

if polizas_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    polizas_validos.to_sql('polizas_curated', engine, if_exists='append', index=False)
    polizas_rechazados.to_sql('polizas_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM polizas_curated LIMIT 10",
    engine
)