# -*- coding: utf-8 -*-
"""etl_siniestros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iS-fwAMDZSYlBqis0qtHSTwGZZaIFtUs
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd
import numpy as np
import re

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

siniestros = pd.read_csv(url)
siniestros.head(20)

#EXPLORACION DE DATOS

#siniestros.shape #filas, columnas
#siniestros.columns
#siniestros.info()
#siniestros.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(siniestros):
    siniestros.columns = (
        siniestros.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return siniestros

# Limpia solamente textos
def limpiar_texto(siniestros):
    for col in siniestros.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        siniestros[col] = siniestros[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        siniestros[col] = siniestros[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return siniestros

#APLICA LIMPIEZA GENERAL
siniestros = normalizar_columnas(siniestros)
siniestros = limpiar_texto(siniestros)
siniestros = siniestros.drop_duplicates() #Elimina duplicados

#LIMPIEZA DE DATOS ESPECIFICOS

#Fecha Siniestros
siniestros["fecha_siniestro"] = pd.to_datetime(
    siniestros["fecha_siniestro"],
    errors="coerce",
    format="mixed"
)

#Monto Siniestros
def limpiar_monto(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().lower()

    # falsos nulos
    if x in ["", "-", "none", "nan", "null"]:
        return np.nan

    # eliminar símbolos (moneda, letras)
    x = re.sub(r"[^\d,.\-]", "", x)

    if "," in x and "." in x:
        # europeo → coma decimal
        if x.rfind(",") > x.rfind("."):
            x = x.replace(".", "").replace(",", ".")
        else:
            x = x.replace(",", "")

    elif x.count(",") > 1:
        # miles con comas
        x = x.replace(",", "")

    elif "," in x:
        # decimal con coma
        x = x.replace(",", ".")

    return x

col = siniestros["monto_siniestro"].apply(limpiar_monto)
siniestros["monto_siniestro"] = pd.to_numeric(col, errors="coerce")

#Estado
siniestros["estado"] = (
    siniestros["estado"].astype(str).str.strip().str.lower().map({
        "abierto":"Abierto",
        "cerrado":"Cerrado",
        "rechazado":"Rechazado"
        })
)

siniestros["estado"] = siniestros["estado"].fillna("No Especificado")

#print(siniestros["monto_siniestro"].astype(str).value_counts().head(20))
#siniestros
#print(siniestros["monto_siniestro"].isna().sum())
#print(siniestros["fecha_siniestro"].isna().sum())
#print(siniestros["estado"].astype(str).value_counts().head(20))

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

columnas = ['fecha_siniestro','monto_siniestro','estado']

datos_invalidos =(
    siniestros[columnas].isin(["No Especificado"]).any(axis=1)|
    siniestros[columnas].isna().any(axis=1)
)

siniestros_validos = siniestros[~datos_invalidos].copy()
siniestros_rechazados = siniestros[datos_invalidos].copy()

# MOTIVO DE RECHAZO

def motivo(row):
    columnas = {
        "fecha_siniestro": "fechaSiniestro_invalida",
        "monto_siniestro": "montoSiniestro_invalido",
        "estado": "estado_invalido"
    }

    motivos = []

    for col, error in columnas.items():
        valor = row[col]

        # condición: nulo o "No Especificado"
        if pd.isna(valor) or str(valor).strip().lower() == "no especificado":
            motivos.append(error)

    return ";".join(motivos)

# aplicar a rechazados
siniestros_rechazados["motivo_rechazo"] = siniestros_rechazados.apply(motivo, axis=1)

#VERIFICAR SI HAY DATOS NULOS
#print(siniestros["estado"] == "No Especificado")
#siniestros_rechazados["motivo_rechazo"].value_counts()

#EXPORTAR ARCHIVOS

siniestros_validos.to_csv("siniestros_curated.csv", index=False)

siniestros_rechazados.to_csv("siniestros_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

if siniestros_validos.empty:
    print("⚠ No hay datos válidos")

if siniestros_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    siniestros_validos.to_sql('siniestros_curated', engine, if_exists='append', index=False)
    siniestros_rechazados.to_sql('siniestros_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM siniestros_rejects LIMIT 10",
    engine
)