# -*- coding: utf-8 -*-
"""etl_aseguradoras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOonCLB2FIY9kOsuiHliHkebPe1PcaS_
"""

#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

aseguradoras = pd.read_csv(url)
aseguradoras.head()

#EXPLORACION DE DATOS

#aseguradoras.shape #filas, columnas
#aseguradoras.columns
#aseguradoras.info()
#aseguradoras.isnull().sum() #cuenta los valores nulos

#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(aseguradoras):
    aseguradoras.columns = (
        aseguradoras.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(r"\s+", "_", regex=True)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return aseguradoras

# Limpia solamente textos
def limpiar_texto(aseguradoras):
    for col in aseguradoras.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        aseguradoras[col] = aseguradoras[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        aseguradoras[col] = aseguradoras[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return aseguradoras

#APLICA LIMPIEZA GENERAL
aseguradoras = normalizar_columnas(aseguradoras)
aseguradoras = limpiar_texto(aseguradoras)
aseguradoras = aseguradoras.drop_duplicates() #Elimina duplicados

#LIMPIEZA DE DATOS ESPECIFICOS

#Nombre
aseguradoras["nombre"] = (
        aseguradoras["nombre"]
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(r"\s+", "_", regex=True)     #Cambia espacios en medio por _
        .str.title()
    )

#Pais
import unicodedata
aseguradoras["pais"] = aseguradoras["pais"].fillna("No Especificado")

aseguradoras["pais"] = (
    aseguradoras["pais"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)

aseguradoras["pais"] = (
    aseguradoras["pais"].astype(str).str.strip().str.lower().replace({
        "costarica":"costa rica",
        "elsalvador":"el salvador"
        }).str.title()
)


#Rating_riesgo
aseguradoras["rating_riesgo"] = (
    aseguradoras["rating_riesgo"].astype(str).str.strip().str.lower().map({
        "a":"alto",
        "alto":"alto",
        "m":"medio",
        "medio":"medio",
        "b":"bajo",
        "bajo":"bajo"
        }).str.title()
)

aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No Especificado")

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

condicion = ["No Especificado"]

aseguradoras_validos = aseguradoras[
    ~aseguradoras[['id_aseguradora','nombre','pais','rating_riesgo']]
    .isin(condicion)
    .any(axis=1)
].copy()

aseguradoras_rechazados = aseguradoras[
    aseguradoras[['id_aseguradora','nombre','pais','rating_riesgo']]
    .isin(condicion)
    .any(axis=1)
].copy()

# MOTIVO DE RECHAZO

def motivo(row):
    motivos = []

    if row['id_aseguradora'] == "No Especificado":
        motivos.append("idAseguradora_noEspecificada")

    if row['nombre'] == "No Especificado":
        motivos.append("nombre_noEspecificado")

    if row['pais'] == "No Especificado":
        motivos.append("pais_noEspecificado")

    if row['rating_riesgo'] == "No Especificado":
        motivos.append("ratingRiesgo_noEspecificado")

    return ";".join(motivos)


# aplicar a rechazados
aseguradoras_rechazados["motivo_rechazo"] = aseguradoras_rechazados.apply(motivo, axis=1)

#EXPORTAR ARCHIVOS

aseguradoras_validos.to_csv("aseguradoras_curated.csv", index=False)

aseguradoras_rechazados.to_csv("aseguradoras_rejects.csv", index=False)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

if aseguradoras_validos.empty:
    print("⚠ No hay datos válidos")

if aseguradoras_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    aseguradoras_validos.to_sql('aseguradoras_curated', engine, if_exists='append', index=False)
    aseguradoras_rechazados.to_sql('aseguradoras_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM aseguradoras_curated LIMIT 10",
    engine
)