# -*- coding: utf-8 -*-
"""etl_clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flnANX_NEPtrhzvcHW1wP1voxcWTs3t8
"""

import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"

df = pd.read_csv(url)
df.head()

#LIMPIEZA DE DATOS

clientes = df.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
  clientes[col]=clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

clientes['email'] = clientes['email'].str.lower()

clientes['fecha_nacimiento']=pd.to_datetime(clientes['fecha_nacimiento'], errors='coerce')

clientes=clientes.drop_duplicates()

#SEPARAR DATOS INVALIDOS Y RECHAZADOS

validos=clientes[
    clientes['nombre'].notna()&
    clientes['email'].notna()
].copy()


rechazados=clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

#EXPORTAR ARCHIVOS

validos.to_csv("clientes_curated.csv", index=False)

rechazados.to_csv("clientes_rejects.csv", index=False)

#MOTIVO DE RECHAZO

def motivo(row):

  motivos=[]

  if pd.isna(row['nombre']):
    motivos.append("nombre_vacio")

  if pd.isna(row['email']):
    motivos.append("email_vacio")

  return ";".join(motivos)

  rechazados["motivo_rechazo"] = rechazados.apply(motivo,axis=1)

#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_9k8q_user:xwqwkBuVuy73PAXR5xRTNnRxAjlvBQoT@dpg-d6qu4ekhg0os73b4fftg-a.oregon-postgres.render.com/etl_seguros_9k8q"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)
print(test)

#CARGAR DATOS EN PostgreSQL

validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM clientes_curated LIMIT 10",
    engine
)